# Generated by Django 4.2.7 on 2023-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_has_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='CVs/'),
        ),
    ]
