# Generated by Django 4.2.7 on 2023-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='career',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='resume',
            new_name='cv',
        ),
        migrations.AddField(
            model_name='application',
            name='recommanded',
            field=models.BooleanField(default=False),
        ),
    ]
