# Generated by Django 4.2.7 on 2023-12-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_career_application_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='recommanded',
            new_name='recommended',
        ),
    ]
