# Generated by Django 4.2.7 on 2023-12-06 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved_by',
            field=models.ManyToManyField(related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='disapproved_by',
            field=models.ManyToManyField(related_name='disapproved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('RECOMMENDED', 'Recommended')], default='SENT', max_length=15),
        ),
    ]
