# Generated by Django 4.2.7 on 2023-12-14 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_rename_career_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('RECOMMENDED', 'Recommended'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], default='SENT', max_length=15),
        ),
    ]
