# Generated by Django 4.2.7 on 2023-12-17 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_application_disliked_by_application_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='disapproved_by',
            field=models.ManyToManyField(blank=True, related_name='disapproved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RECOMMENDED', 'Recommended'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], default='SUBMITTED', max_length=15),
        ),
    ]
