# Generated by Django 4.2.7 on 2024-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_application_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cv',
            new_name='cv1',
        ),
        migrations.AddField(
            model_name='application',
            name='certificate1',
            field=models.FileField(null=True, upload_to='CVs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate2',
            field=models.FileField(null=True, upload_to='CVs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate3',
            field=models.FileField(null=True, upload_to='CVs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate4',
            field=models.FileField(null=True, upload_to='CVs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv2',
            field=models.FileField(null=True, upload_to='CVs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv3',
            field=models.FileField(null=True, upload_to='CVs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv4',
            field=models.FileField(null=True, upload_to='CVs/'),
        ),
    ]
