# Generated by Django 4.2.7 on 2024-03-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_cv_application_cv1_application_certificate1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificate1',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='certificate2',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='certificate3',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='certificate4',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv2',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv3',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv4',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
    ]
