# Generated by Django 4.2.7 on 2024-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_application_certificate1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='box1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='box2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='box3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='box4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='box5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='box6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='box7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='box8',
            field=models.BooleanField(default=False),
        ),
    ]
